cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules

stages:
#  - validateinfra
#  - planinfra
#  - applyinfra
  - build
  - test
#  - deploy
#
# .init:
#   image:
#     name: hashicorp/terraform:light
#     entrypoint:
#       - '/usr/bin/env'
#       - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
#   before_script:
#     - rm -rf .terraform
#     - terraform --version
#     - mkdir -p /creds
#     - echo $SERVICE_ACCOUNT_KEY | base64 -d
#     - echo $SERVICE_ACCOUNT_KEY | base64 -d > /creds/serviceaccount.json
#     - export GOOGLE_APPLICATION_CREDENTIALS="/creds/serviceaccount.json"
#     - echo $GOOGLE_APPLICATION_CREDENTIALS
#     - cat $GOOGLE_APPLICATION_CREDENTIALS
#     - terraform init
#
# validateinfra:
#   stage: validateinfra
#   extends: .init
#   script:
#     - terraform validate
#     - terraform fmt
#
# planinfra:
#   stage: planinfra
#   extends: .init
#   script:
#     - terraform plan -out "planfile"
#     - cat $GOOGLE_APPLICATION_CREDENTIALS
#   dependencies:
#     - validateinfra
#   artifacts:
#     paths:
#       - planfile
#
# applyinfra:
#   stage: applyinfra
#   extends: .init
#   script:
#     - terraform apply -input=false planfile
#   dependencies:
#     - planinfra
#   when: manual
#
build:
  image: node
  stage: build
  script:
    npm install
    npm start
  artifacts:
    paths:
      - ./public

test:
  image: node
  stage: test
  script:
    - npm install
    - npm start &
    - sleep 3
    - curl "http://localhost:5000" | tac | tac | grep -q "Getting Started with Node on Heroku"
